### ISSUE TITLE
requests.exceptions.ReadTimeout

### ISSUE THREAD

**Issue by LimeDrive** [YggNode/yggnode#12]
[https://i.imgur.com/bzwkDDA.png](url)

Sa fonctionne sur restart on-failure mais... 
restart intempestif du container, faut vraiment géré cette erreur qui fout le script en code d'exit assez souvent.

```py
Traceback (most recent call last):
resync          |   File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 445, in _make_request
resync          |     six.raise_from(e, None)
resync          |   File "<string>", line 3, in raise_from
resync          |   File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 440, in _make_request
resync          |     httplib_response = conn.getresponse()
resync          |   File "/usr/local/lib/python3.9/http/client.py", line 1345, in getresponse
resync          |     response.begin()
resync          |   File "/usr/local/lib/python3.9/http/client.py", line 307, in begin
resync          |     version, status, reason = self._read_status()
resync          |   File "/usr/local/lib/python3.9/http/client.py", line 268, in _read_status
resync          |     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
resync          |   File "/usr/local/lib/python3.9/socket.py", line 704, in readinto
resync          |     return self._sock.recv_into(b)
resync          |   File "/usr/local/lib/python3.9/ssl.py", line 1241, in recv_into
resync          |     return self.read(nbytes, buffer)
resync          |   File "/usr/local/lib/python3.9/ssl.py", line 1099, in read
resync          |     return self._sslobj.read(len, buffer)
resync          | socket.timeout: The read operation timed out
resync          | 
resync          | During handling of the above exception, another exception occurred:
resync          | 
resync          | Traceback (most recent call last):
resync          |   File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
resync          |     resp = conn.urlopen(
resync          |   File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
resync          |     retries = retries.increment(
resync          |   File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 532, in increment
resync          |     raise six.reraise(type(error), error, _stacktrace)
resync          |   File "/usr/local/lib/python3.9/site-packages/urllib3/packages/six.py", line 735, in reraise
resync          |     raise value
resync          |   File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
resync          |     httplib_response = self._make_request(
resync          |   File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 447, in _make_request
resync          |     self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
resync          |   File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 336, in _raise_timeout
resync          |     raise ReadTimeoutError(
resync          | urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='www4.yggtorrent.li', port=443): Read timed out. (read timeout=25)
resync          | 
resync          | During handling of the above exception, another exception occurred:
resync          | 
resync          | Traceback (most recent call last):
resync          |   File "/yggnode-resync/resync.py", line 101, in <module>
resync          |     rssString = getFromCategory(str(idCat), cookies, catList, serverConfiguration["yggDomainName"], logging)
resync          |   File "/yggnode-resync/resync.py", line 19, in getFromCategory
resync          |     return (requests.get(url, cookies=CFcookies, headers=headers, timeout=25)).text
resync          |   File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 76, in get
resync          |     return request('get', url, params=params, **kwargs)
resync          |   File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 61, in request
resync          |     return session.request(method=method, url=url, **kwargs)
resync          |   File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
resync          |     resp = self.send(prep, **send_kwargs)
resync          |   File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
resync          |     r = adapter.send(request, **kwargs)
resync          |   File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 529, in send
resync          |     raise ReadTimeout(e, request=request)
resync          | requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='www4.yggtorrent.li', port=443): Read timed out. (read timeout=25)
```

To keep logs track. Must be except:

**Comment by YggNode** [comment]
Totalement!

**Comment by LimeDrive** [comment]
'requests.exceptions.ReadTimeout' is parent of 'requests.exceptions.RequestException'

```py
@retry(tries=5, delay=60, jitter=10, logger=logging)
def get_Rss_Feed(cookies):
    try:
        return getFromCategory(str(idCat), cookies, catList, serverConfiguration["yggDomainName"])
    except (ConnectionError, requests.exceptions.RequestException) as e:
        logging.warning(            f"Connection fails try fix : {e}")
        cookies = getCookies(FlaresolverrPath, serverConfiguration["yggDomainName"])
        logging.info(
            f"New cookies : {str(cookies)} ")
        raise
```
